### ISSUE TITLE
Allow running multiple commands

### ISSUE THREAD

**Issue by mTsBucy1** [Miyoshi-Ryota/async-ssh2-tokio#12]
Currently, one has to reconnect (i.e. call `Client::connect`) before every invocation of `Client::execute`.
I believe it would be preferable to fix this, so that one can call execute as often as needed.

Internally I see no reason for this not to be implemented, my fix delays the call to `channel_open_session` until the beginning of the execute method. See https://github.com/mTsBucy1/async-ssh2-tokio-fork/commit/d51e5e103232d0dbaf0f4ac00e5398bd2787e717

A even more elegant fix would be to connect in the constructor of the client. Then the type system ensures that when there exists a `Client`, it is (or at least once was) connected and authenticated. I, again, see no reason for having an unconnected `Client` instance.

[My fork](https://github.com/mTsBucy1/async-ssh2-tokio-fork) also addressed some other ergonomic, but breaking, changes. Thus a simple PR will not suffice. I believe my changes are improvements, but I'm open to any discussion if that gets those changes merged (in a new incompatible 0.4.0 version).

Lastly, what's your status on this project, should I try to help with the development of this crate, or have you abandoned it and should I rather work on my fork?

**Comment by Miyoshi-Ryota** [comment]
@mTsBucy1 
### Summary
Thank you for your work. 🥳🌟
I have already reviewed your fork (https://github.com/mTsBucy1/async-ssh2-tokio-fork/commit/d51e5e103232d0dbaf0f4ac00e5398bd2787e717). I also think your fork is awesome.🌟 And I want to merge your fork to this original repository!! Could you create a pull request? 

### Detail
> [My fork](https://github.com/mTsBucy1/async-ssh2-tokio-fork) also addressed some other ergonomic, but breaking, changes. Thus a simple PR will not suffice. I believe my changes are improvements, but I'm open to any discussion if that gets those changes merged (in a new incompatible 0.4.0 version).

I already reviewed your work. I think it's a good change and I want to merge it.

> Currently, one has to reconnect (i.e. call Client::connect) before every invocation of Client::execute. I believe it would be preferable to fix this, so that one can call execute as often as needed.

I was aware of the problem and wanted to fix it, but it was left untouched. Your work is a very useful fix.

> A even more elegant fix would be to connect in the constructor of the client. Then the type system ensures that when there exists a Client, it is (or at least once was) connected and authenticated. I, again, see no reason for having an unconnected Client instance.

I think this change is also nice. If you make this change, I'll merge it immediately. 

> Lastly, what's your status on this project, should I try to help with the development of this crate, or have you abandoned it and should I rather work on my fork?

This project is still active. It would be great if you help develop this crete. 🥰

**Comment by mTsBucy1** [comment]
Opening multiple sessions within the same connection is not the way to go to execute many commands.
There seem to be two options, debatable with is better:
1. Opening a shell and executing all commands on the same session.
2. Reconnecting for every command.

Option 1 would maybe fix #3, but may come with all the shell weirdness such as ANSI escape sequences.
Option 2 would be more straightforward, but constant reauthentication might be undesirable.

I'll implement option 2 (which is mostly a revert on my fork) for now.

**Comment by mTsBucy1** [comment]
Resolved with #13

**Comment by mTsBucy1** [comment]
I would like to mention that https://github.com/warp-tech/russh/pull/118 fixed an issue, where the channels where not properly closed. Therefore my previous comment is invalid and my revert can be reverted (again just establishing a connection in the constructor).

I'm sorry for the confusion and I'm sorry that I can't deal with this myself right now, but hopefully this is helpful for any future work.

**Comment by mwileczka** [comment]
@Miyoshi-Ryota @mTsBucy1 I would highly suggest going back to using one connection. The problem wasn't the limit from sshd config, the problem was russh not closing out completed channels. Very recently, russh has been fixed so you can now run as many executes as you want on one connection, with up to 10 concurrent (or whatever is in your sshd config).

**Comment by mTsBucy1** [comment]
@mwileczka I agree! If you're able to, please create a pull request for this. Everything you need should be in the git history. Sadly I haven't got the time right now, even though it shouldn't take more than 1-2 hours.

**Comment by mwileczka** [comment]
@mTsBucy1 Wow, i'm sorry, I completely missed your last comment, clearly you already knew about it. 🤦‍♂️ I will submit a PR though to help out.
