### ISSUE TITLE
Add key authentification

### ISSUE THREAD

**Issue by mTsBucy1** [Miyoshi-Ryota/async-ssh2-tokio#15]
Authentification with ssh keys seems like an important feature.

I've found the repo `there` ([relevant file](https://github.com/queer/that-goes-there/blob/d87f72b56661dffac4854c57d71f5a4925c6f611/libthere/src/executor/ssh.rs)) that has a working implementation, as a reference.

**Comment by Miyoshi-Ryota** [comment]
solved by https://github.com/Miyoshi-Ryota/async-ssh2-tokio/pull/19
