### ISSUE TITLE
Need Help. I am getting error with using private key as auth method

### ISSUE THREAD

**Issue by KunalSin9h** [Miyoshi-Ryota/async-ssh2-tokio#36]
I am getting `InvalidKey(Key not supported)` error.

This is my code.

![image](https://github.com/Miyoshi-Ryota/async-ssh2-tokio/assets/82411321/4b3657a0-f4bb-4a3c-8cba-ebc5446ced9e)

**Comment by Miyoshi-Ryota** [comment]
thank you for your comment, I'll check your issue later.

**Comment by Miyoshi-Ryota** [comment]
@KunalSin9h 
The list of supported key types can be found in the readme of the repository below. It's a separate repository, but our library supports the same keys as this one. 

https://github.com/warp-tech/russh

I suspect your key file is not an unsupported algorithm.

**Comment by KunalSin9h** [comment]
Thanks for your reply. 
I have two general question?
1. Does we need public key for connecting to remote server with ssh. Because it seems `russh` is using public key for authentication. 
2. When i will use `with_key` auth_method, then what should be the value of ServerCheckMethod ?
![image](https://github.com/Miyoshi-Ryota/async-ssh2-tokio/assets/82411321/4c546a9f-2a29-4474-b476-f2d165f53b9e)

Thanks in advance

**Comment by Miyoshi-Ryota** [comment]
@KunalSin9h 
> Does we need public key for connecting to remote server with ssh. Because it seems russh is using public key for authentication.

In the sense of ordinary key authentication, it is necessary to list the public key in ~/.ssh/authorized_keys on the remote server. You need to be able to use ssh using commands, but there is no need to install it on the client side.


> When i will use with_key auth_method, then what should be the value of ServerCheckMethod ?

NoCheck is fine. This option allows connections to be made to any server, even if it is a spoofed server. See also following a test code.

https://github.com/Miyoshi-Ryota/async-ssh2-tokio/blob/3da44a1fe6ea1f88b7b1837a9d310a6543504822/src/client.rs#L578-L587

**Comment by Miyoshi-Ryota** [comment]
Could you update our library and use key created by `ssh-keygen -t ed25519`?

**Comment by KunalSin9h** [comment]
@Miyoshi-Ryota 

> Could you update our library and use a key created by `ssh-keygen -t ed25519`?

"our library", this is meant for `async-ssh2-tokio` lib? and use key in tests?

**Comment by Miyoshi-Ryota** [comment]
@KunalSin9h 
> "our library", this is meant for async-ssh2-tokio lib?

Yes.  When you update async-ssh2-tokio, dependent library(russh-keys) will also be updated automatically. These updates also include improvements to error messages.

>  and use key in tests?

No. You create your new key by `ssh-keygen -t ed25519` command. 

For example, keys created with `ssh-keygen -t dsa` command are not supported, and an error like a `InvalidKey(Key not supported)` will be sent when you try to use them. You should use a key supported by russh-keys for ssh. (and ed25519 are supported by russh-keys library.)

**Comment by KunalSin9h** [comment]
Ok will check using an `ed25519` key...
