### ISSUE TITLE
Not working with domain names (at least on macOs)

### ISSUE THREAD

**Issue by cybersoulK** [Miyoshi-Ryota/async-ssh2-tokio#40]
ServerCheckMethod::DefaultKnownHostsFile or ServerCheckMethod::KnownHostsFile(...) Fail
```rust
error: "Err(Unknown server key)"
```

my known_hosts has the domain name listed.
async-ssh2-tokio seems to convert my domain to an IP and passes it to russh, where it will try to match it against the domain in known_hosts, and that fails

**Comment by cybersoulK** [comment]
i found a fix for this if i can merge it?

**Comment by Miyoshi-Ryota** [comment]
@cybersoulK 
Yes! If you fix this, I'll merge your pull request! ( and I appreciate you! )

**Comment by cybersoulK** [comment]
there are 3 ways to fix this issue.
The original hostname has to be preserved.

1. replace ToAddrSockets by (&str, u16)
2. add Option<String>
3. create a Custom trait and implement everything that ToAddrSockets does.

I will submit Prs for 1 and 3 and you can decide
