### ISSUE TITLE
Why didn't you see the use of tokio in the source code?

### ISSUE THREAD

**Issue by TheBlindM** [Miyoshi-Ryota/async-ssh2-tokio#56]

**Comment by Miyoshi-Ryota** [comment]
@TheBlindM 
I do not fully understand your question, but I will try to answer it. Sorry if I have missed the point.

It is expected that tokio is used as runtime in russh, the underlying library.
So this library also expects tokio to be used as runtime. There is a possibility that it might be possible to run it with something other than tokio, but I don't know.

https://github.com/search?q=repo%3Awarp-tech%2Frussh%20tokio&type=code

**Comment by TheBlindM** [comment]
> @TheBlindM I do not fully understand your question, but I try to answer it. Sorry if I have missed the point.
> 
> It is expected that tokio is used as runtime in russh, the underlying library. So this library also expects tokio to be used as runtime. There is a possibility that it might be possible to run it with something other than tokio, but I don't know.
> 
> https://github.com/search?q=repo%3Awarp-tech%2Frussh%20tokio&type=code


`    async fn exec(
        session: &Mutex<client::Handle<tty::ssh::SshClient>>,
        command: String,
    ) -> Result<Option<String>> {
        let mut channel = session.lock().await.channel_open_session().await?;

        channel.exec(true, command).await?;

        let mut result: Option<String> = None;
        let mut exit_status: Option<u32> = None;

        while let Some(msg) = channel.wait().await {
            match msg {
                ChannelMsg::Data { data } => {
                    let data_str = match String::from_utf8(data.to_vec()) {
                        Ok(s) => s,
                        Err(_) => continue, // Skip or handle the error as you see fit
                    };

                    result = match result {
                        Some(ref mut existing_string) => {
                            existing_string.push_str(&data_str); // Append the data to the existing string
                            Some(existing_string.clone()) // This line is technically unnecessary but included for clarity
                        }
                        None => Some(data_str), // Initialize result with the first chunk of data
                    };
                }
                ChannelMsg::ExitStatus {
                    exit_status: status,
                } => {
                    exit_status = Some(status);
                }
                _ => {}
            }
        }
        channel.close().await?;
        if exit_status != Some(0) {
            return Err(anyhow::anyhow!(
                "Command exited with status: {:?}",
                exit_status
            ));
        }

        Ok(result)
    }`


The situation I am currently facing is as follows: when using tauri and # [tokio:: main] environment, there is a method that is called once per second, but after being called multiple times, it will block in "channel. wait(). await". This situation only occurs on this high latency server, but if I call the main method multiple times in a simple # [tokio:: main] demo, it will not block

**Comment by Miyoshi-Ryota** [comment]
@TheBlindM 
From the information you have given us, I can only make a prediction.

Usually sshd has a limit on the number of sessions and channels. In tauri's environment, the exec function is probably being called by a method such as tokio::spawn, which opens number of channels at the same time, and the number of channels is reaching those limits. 

On the other hand, if you simply call the function multiple times in simple [tokio::main], it is only processed one by one, so it did not reach those limits.

This is not my library code, so I don't think this is the right place to ask.

**Comment by TheBlindM** [comment]
> @TheBlindM From the information you have given us, I can only make a prediction. 根据你给我们的信息，我只能做出一个预测。
> 
> Usually sshd has a limit on the number of sessions and channels. In tauri's environment, the exec function is probably being called by a method such as tokio::spawn, which opens number of channels at the same time, and the number of channels is reaching those limits.通常 sshd 对会话和通道的数量有限制。在tauri的环境中，exec函数可能被诸如tokio::spawn之类的方法调用，该方法同时打开多个通道，并且通道的数量已达到这些限制。
> 
> On the other hand, if you simply call the function multiple times in simple [tokio::main], it is only processed one by one, so it did not reach those limits.另一方面，如果您只是在简单的 [tokio::main] 中多次调用该函数，它只会被一个接一个地处理，因此它没有达到这些限制。
> 
> This is not my library code, so I don't think this is the right place to ask.这不是我的图书馆代码，所以我认为这不是提问的正确地方。



> @TheBlindM From the information you have given us, I can only make a prediction.
> 
> Usually sshd has a limit on the number of sessions and channels. In tauri's environment, the exec function is probably being called by a method such as tokio::spawn, which opens number of channels at the same time, and the number of channels is reaching those limits.
> 
> On the other hand, if you simply call the function multiple times in simple [tokio::main], it is only processed one by one, so it did not reach those limits.
> 
> This is not my library code, so I don't think this is the right place to ask.

Okay, thank you for your reply
